/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation;

import fr.minesnantes.browserautomation.AbstractSeleniumDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SeleniumDSLRuntimeModule extends AbstractSeleniumDSLRuntimeModule {
}
