/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.seleniumDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.minesnantes.browserautomation.seleniumDSL.Assert#getSearch <em>Search</em>}</li>
 *   <li>{@link fr.minesnantes.browserautomation.seleniumDSL.Assert#getValue <em>Value</em>}</li>
 *   <li>{@link fr.minesnantes.browserautomation.seleniumDSL.Assert#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getAssert()
 * @model
 * @generated
 */
public interface Assert extends Instruction
{
  /**
   * Returns the value of the '<em><b>Search</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Search</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Search</em>' attribute.
   * @see #setSearch(String)
   * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getAssert_Search()
   * @model
   * @generated
   */
  String getSearch();

  /**
   * Sets the value of the '{@link fr.minesnantes.browserautomation.seleniumDSL.Assert#getSearch <em>Search</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Search</em>' attribute.
   * @see #getSearch()
   * @generated
   */
  void setSearch(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getAssert_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link fr.minesnantes.browserautomation.seleniumDSL.Assert#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getAssert_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.minesnantes.browserautomation.seleniumDSL.Assert#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Assert
