/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.seleniumDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getInstruction()
 * @model
 * @generated
 */
public interface Instruction extends EObject
{
} // Instruction
