/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.seleniumDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Procedure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.minesnantes.browserautomation.seleniumDSL.Procedure#getName <em>Name</em>}</li>
 *   <li>{@link fr.minesnantes.browserautomation.seleniumDSL.Procedure#getParameters <em>Parameters</em>}</li>
 *   <li>{@link fr.minesnantes.browserautomation.seleniumDSL.Procedure#getInstructions <em>Instructions</em>}</li>
 * </ul>
 *
 * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getProcedure()
 * @model
 * @generated
 */
public interface Procedure extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getProcedure_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link fr.minesnantes.browserautomation.seleniumDSL.Procedure#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Parameters</b></em>' attribute list.
	 * The list contents are of type {@link java.lang.String}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Parameters</em>' attribute list.
	 * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getProcedure_Parameters()
	 * @model unique="false"
	 * @generated
	 */
  EList<String> getParameters();

  /**
	 * Returns the value of the '<em><b>Instructions</b></em>' containment reference list.
	 * The list contents are of type {@link fr.minesnantes.browserautomation.seleniumDSL.Instruction}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instructions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Instructions</em>' containment reference list.
	 * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getProcedure_Instructions()
	 * @model containment="true"
	 * @generated
	 */
  EList<Instruction> getInstructions();

} // Procedure
