/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.seleniumDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Selenium Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.minesnantes.browserautomation.seleniumDSL.SeleniumTest#getProcedures <em>Procedures</em>}</li>
 *   <li>{@link fr.minesnantes.browserautomation.seleniumDSL.SeleniumTest#getMain <em>Main</em>}</li>
 * </ul>
 *
 * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getSeleniumTest()
 * @model
 * @generated
 */
public interface SeleniumTest extends EObject
{
  /**
   * Returns the value of the '<em><b>Procedures</b></em>' containment reference list.
   * The list contents are of type {@link fr.minesnantes.browserautomation.seleniumDSL.Procedure}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Procedures</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedures</em>' containment reference list.
   * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getSeleniumTest_Procedures()
   * @model containment="true"
   * @generated
   */
  EList<Procedure> getProcedures();

  /**
   * Returns the value of the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Main</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' containment reference.
   * @see #setMain(MainProcedure)
   * @see fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage#getSeleniumTest_Main()
   * @model containment="true"
   * @generated
   */
  MainProcedure getMain();

  /**
   * Sets the value of the '{@link fr.minesnantes.browserautomation.seleniumDSL.SeleniumTest#getMain <em>Main</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' containment reference.
   * @see #getMain()
   * @generated
   */
  void setMain(MainProcedure value);

} // SeleniumTest
