/*
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.parser.antlr;

import com.google.inject.Inject;
import fr.minesnantes.browserautomation.parser.antlr.internal.InternalSeleniumDSLParser;
import fr.minesnantes.browserautomation.services.SeleniumDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SeleniumDSLParser extends AbstractAntlrParser {

	@Inject
	private SeleniumDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSeleniumDSLParser createParser(XtextTokenStream stream) {
		return new InternalSeleniumDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SeleniumTest";
	}

	public SeleniumDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SeleniumDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
