/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.validation;

import fr.minesnantes.browserautomation.validation.AbstractSeleniumDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SeleniumDSLValidator extends AbstractSeleniumDSLValidator {
}
