/*
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SeleniumDSLRuntimeModule extends AbstractSeleniumDSLRuntimeModule {
}
