/*
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SeleniumDSLStandaloneSetup extends SeleniumDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new SeleniumDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
