/*
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.tests

import com.google.inject.Inject
import fr.minesnantes.browserautomation.seleniumDSL.SeleniumTest
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(SeleniumDSLInjectorProvider)
class SeleniumDSLParsingTest{

	@Inject
	ParseHelper<SeleniumTest> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
