/*
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSeleniumDSLScopeProvider extends DelegatingScopeProvider {
}
