/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.ui.contentassist;

import fr.minesnantes.browserautomation.ui.contentassist.AbstractSeleniumDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SeleniumDSLProposalProvider extends AbstractSeleniumDSLProposalProvider {
}
