/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.ui;

import fr.minesnantes.browserautomation.ui.AbstractSeleniumDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SeleniumDSLUiModule extends AbstractSeleniumDSLUiModule {
  public SeleniumDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
