/*
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSeleniumDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLPackage.eINSTANCE);
		return result;
	}
	
}
