/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.generator;

@SuppressWarnings("all")
public class Counter {
  private int count;
  
  public int Counter() {
    return this.count = 0;
  }
  
  public int nextCount() {
    return this.count++;
  }
}
