/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.generator;

import com.google.common.collect.Iterables;
import fr.minesnantes.browserautomation.generator.Counter;
import fr.minesnantes.browserautomation.seleniumDSL.Assert;
import fr.minesnantes.browserautomation.seleniumDSL.CallProcedure;
import fr.minesnantes.browserautomation.seleniumDSL.Click;
import fr.minesnantes.browserautomation.seleniumDSL.Fill;
import fr.minesnantes.browserautomation.seleniumDSL.Instruction;
import fr.minesnantes.browserautomation.seleniumDSL.MainProcedure;
import fr.minesnantes.browserautomation.seleniumDSL.Navigate;
import fr.minesnantes.browserautomation.seleniumDSL.Procedure;
import fr.minesnantes.browserautomation.seleniumDSL.Read;
import fr.minesnantes.browserautomation.seleniumDSL.Select;
import fr.minesnantes.browserautomation.seleniumDSL.SeleniumTest;
import fr.minesnantes.browserautomation.seleniumDSL.Tick;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class SeleniumDSLGenerator extends AbstractGenerator {
  private HashMap<String, List<String>> proceduresContext;
  
  private Counter elementCounter;
  
  public HashMap<String, List<String>> initializeContext() {
    HashMap<String, List<String>> _xblockexpression = null;
    {
      Counter _counter = new Counter();
      this.elementCounter = _counter;
      HashMap<String, List<String>> _hashMap = new HashMap<String, List<String>>();
      _xblockexpression = this.proceduresContext = _hashMap;
    }
    return _xblockexpression;
  }
  
  public HashMap<String, List<String>> destroyContext() {
    HashMap<String, List<String>> _xblockexpression = null;
    {
      this.elementCounter = null;
      _xblockexpression = this.proceduresContext = null;
    }
    return _xblockexpression;
  }
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    this.initializeContext();
    EList<EObject> _contents = resource.getContents();
    Iterable<SeleniumTest> _filter = Iterables.<SeleniumTest>filter(_contents, SeleniumTest.class);
    SeleniumTest _head = IterableExtensions.<SeleniumTest>head(_filter);
    CharSequence _generateSeleniumTest = this.generateSeleniumTest(_head);
    fsa.generateFile(
      (("browserautomation" + File.separator) + "SeleniumTest.java"), _generateSeleniumTest);
    this.destroyContext();
  }
  
  public CharSequence generateSeleniumTest(final SeleniumTest st) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package browserautomation;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.openqa.selenium.By;");
    _builder.newLine();
    _builder.append("import org.openqa.selenium.WebDriver;");
    _builder.newLine();
    _builder.append("import org.openqa.selenium.WebElement;");
    _builder.newLine();
    _builder.append("import org.openqa.selenium.chrome.ChromeDriver;");
    _builder.newLine();
    _builder.append("import org.openqa.selenium.support.ui.Select;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class SeleniumTest {");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private static WebDriver webDriver;");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    EList<Procedure> _procedures = st.getProcedures();
    final Function1<Procedure, String> _function = (Procedure p) -> {
      StringConcatenation _builder_1 = new StringConcatenation();
      EList<String> _parameters = p.getParameters();
      final Function1<String, String> _function_1 = (String par) -> {
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.append("String ");
        _builder_2.append(par, "");
        return _builder_2.toString();
      };
      List<String> _map = ListExtensions.<String, String>map(_parameters, _function_1);
      final String params = IterableExtensions.join(_map, ", ");
      _builder_1.newLineIfNotEmpty();
      _builder_1.append("private static void ");
      String _name = p.getName();
      _builder_1.append(_name, "");
      _builder_1.append(" (");
      _builder_1.append(params, "");
      _builder_1.append(") {");
      _builder_1.newLineIfNotEmpty();
      _builder_1.append("    ");
      String _name_1 = p.getName();
      EList<String> _parameters_1 = p.getParameters();
      List<String> _put = this.proceduresContext.put(_name_1, _parameters_1);
      _builder_1.append(_put, "    ");
      _builder_1.newLineIfNotEmpty();
      _builder_1.append("    ");
      EList<Instruction> _instructions = p.getInstructions();
      final Function1<Instruction, CharSequence> _function_2 = (Instruction i) -> {
        String _name_2 = p.getName();
        return this.generateInstruction(i, _name_2);
      };
      List<CharSequence> _map_1 = ListExtensions.<Instruction, CharSequence>map(_instructions, _function_2);
      String _join = IterableExtensions.join(_map_1);
      _builder_1.append(_join, "    ");
      _builder_1.newLineIfNotEmpty();
      _builder_1.append("}");
      _builder_1.newLine();
      return _builder_1.toString();
    };
    List<String> _map = ListExtensions.<Procedure, String>map(_procedures, _function);
    String _join = IterableExtensions.join(_map);
    _builder.append(_join, "    ");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Initialize Selenium web driver for Google Chrome");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("System.setProperty(\"webdriver.chrome.driver\", \"lib/chromedriver\");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("webDriver = new ChromeDriver();");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("        ");
    ArrayList<String> _arrayList = new ArrayList<String>();
    List<String> _put = this.proceduresContext.put("main", _arrayList);
    _builder.append(_put, "        ");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    MainProcedure _main = st.getMain();
    EList<Instruction> _instructions = _main.getInstructions();
    final Function1<Instruction, CharSequence> _function_1 = (Instruction i) -> {
      return this.generateInstruction(i, "main");
    };
    List<CharSequence> _map_1 = ListExtensions.<Instruction, CharSequence>map(_instructions, _function_1);
    String _join_1 = IterableExtensions.join(_map_1);
    _builder.append(_join_1, "        ");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Close the browser");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("webDriver.quit();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Navigate n, final String methodName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("webDriver.get(\"");
    String _url = n.getUrl();
    _builder.append(_url, "");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Click c, final String methodName) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    final String clickValue = c.getValue();
    _builder.newLineIfNotEmpty();
    CharSequence _switchResult = null;
    String _type = c.getType();
    switch (_type) {
      case "input":
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.append("WebElement ");
        _builder_2.append(eltName, "");
        _builder_2.append(" = webDriver.findElement(By.xpath(\"//input[@value=\\\"");
        _builder_2.append(clickValue, "");
        _builder_2.append("\\\"]\"));");
        _switchResult = _builder_2;
        break;
      case "link":
        StringConcatenation _builder_3 = new StringConcatenation();
        _builder_3.append("WebElement ");
        _builder_3.append(eltName, "");
        _builder_3.append(" = webDriver.findElement(By.linkText(\"");
        _builder_3.append(clickValue, "");
        _builder_3.append("\"));");
        _switchResult = _builder_3;
        break;
      case "xpath":
        StringConcatenation _builder_4 = new StringConcatenation();
        _builder_4.append("WebElement ");
        _builder_4.append(eltName, "");
        _builder_4.append(" = webDriver.findElement(By.xpath(\"");
        _builder_4.append(clickValue, "");
        _builder_4.append("\"));");
        _switchResult = _builder_4;
        break;
      case "name":
        StringConcatenation _builder_5 = new StringConcatenation();
        _builder_5.append("WebElement ");
        _builder_5.append(eltName, "");
        _builder_5.append(" = webDriver.findElement(By.name(\"");
        _builder_5.append(clickValue, "");
        _builder_5.append("\"));");
        _switchResult = _builder_5;
        break;
      default:
        StringConcatenation _builder_6 = new StringConcatenation();
        _builder_6.append("// FIXME unrecognized click instruction: click ");
        String _type_1 = c.getType();
        _builder_6.append(_type_1, "");
        _builder_6.append(" ");
        _builder_6.append(clickValue, "");
        _switchResult = _builder_6;
        break;
    }
    _builder.append(_switchResult, "");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".click();");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Fill f, final String methodName) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    _builder.append("WebElement ");
    _builder.append(eltName, "");
    _builder.append(" = webDriver.findElement(By.name(\"");
    String _name = f.getName();
    _builder.append(_name, "");
    _builder.append("\"));");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".clear();");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".sendKeys(");
    {
      List<String> _get = this.proceduresContext.get(methodName);
      String _value = f.getValue();
      boolean _contains = _get.contains(_value);
      if (_contains) {
        String _value_1 = f.getValue();
        _builder.append(_value_1, "");
      } else {
        _builder.append("\"");
        String _value_2 = f.getValue();
        _builder.append(_value_2, "");
        _builder.append("\"");
      }
    }
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Tick t, final String methodName) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    _builder.append("WebElement ");
    _builder.append(eltName, "");
    _builder.append(" = webDriver.findElement(By.name(\"");
    String _name = t.getName();
    _builder.append(_name, "");
    _builder.append("\"));");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".click();");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Select s, final String methodName) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    _builder.append("Select ");
    _builder.append(eltName, "");
    _builder.append(" = new Select(webDriver.findElement(By.name(\"");
    String _name = s.getName();
    _builder.append(_name, "");
    _builder.append("\")));");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".selectByVisibleText(\"");
    String _value = s.getValue();
    _builder.append(_value, "");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Read r, final String methodName) {
    CharSequence _xblockexpression = null;
    {
      List<String> _get = this.proceduresContext.get(methodName);
      String _variable = r.getVariable();
      _get.add(_variable);
      StringConcatenation _builder = new StringConcatenation();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("element");
      int _nextCount = this.elementCounter.nextCount();
      _builder_1.append(_nextCount, "");
      final String eltName = _builder_1.toString();
      _builder.newLineIfNotEmpty();
      _builder.append("WebElement ");
      _builder.append(eltName, "");
      _builder.append(" = webDriver.findElement(By.name(\"");
      String _name = r.getName();
      _builder.append(_name, "");
      _builder.append("\"));");
      _builder.newLineIfNotEmpty();
      _builder.append("String ");
      String _variable_1 = r.getVariable();
      _builder.append(_variable_1, "");
      _builder.append(" = ");
      _builder.append(eltName, "");
      _builder.append(".getAttribute(\"value\");");
      _builder.newLineIfNotEmpty();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }
  
  protected CharSequence _generateInstruction(final Assert a, final String methodName) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    final String assertName = a.getName();
    _builder.newLineIfNotEmpty();
    final String assertValue = a.getValue();
    _builder.newLineIfNotEmpty();
    CharSequence _switchResult = null;
    String _type = a.getType();
    switch (_type) {
      case "input":
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.append("WebElement ");
        _builder_2.append(eltName, "");
        _builder_2.append(" = webDriver.findElement(By.xpath(\"//input[@value=\\\"");
        _builder_2.append(assertName, "");
        _builder_2.append("\\\"]\"));");
        _switchResult = _builder_2;
        break;
      case "link":
        StringConcatenation _builder_3 = new StringConcatenation();
        _builder_3.append("WebElement ");
        _builder_3.append(eltName, "");
        _builder_3.append(" = webDriver.findElement(By.linkText(\"");
        _builder_3.append(assertName, "");
        _builder_3.append("\"));");
        _switchResult = _builder_3;
        break;
      case "xpath":
        StringConcatenation _builder_4 = new StringConcatenation();
        _builder_4.append("WebElement ");
        _builder_4.append(eltName, "");
        _builder_4.append(" = webDriver.findElement(By.xpath(\"");
        _builder_4.append(assertName, "");
        _builder_4.append("\"));");
        _switchResult = _builder_4;
        break;
      case "name":
        StringConcatenation _builder_5 = new StringConcatenation();
        _builder_5.append("WebElement ");
        _builder_5.append(eltName, "");
        _builder_5.append(" = webDriver.findElement(By.name(\"");
        _builder_5.append(assertName, "");
        _builder_5.append("\"));");
        _switchResult = _builder_5;
        break;
      default:
        StringConcatenation _builder_6 = new StringConcatenation();
        _builder_6.append("// FIXME unrecognized assert instruction: assert ");
        String _type_1 = a.getType();
        _builder_6.append(_type_1, "");
        _builder_6.append(" ");
        _builder_6.append(assertName, "");
        _switchResult = _builder_6;
        break;
    }
    _builder.append(_switchResult, "");
    _builder.newLineIfNotEmpty();
    CharSequence _switchResult_1 = null;
    String _method = a.getMethod();
    switch (_method) {
      case "contains":
        StringConcatenation _builder_6 = new StringConcatenation();
        _builder_6.append("if(!");
        _builder_6.append(eltName, "");
        _builder_6.append(".getText().contains(");
        {
          List<String> _get = this.proceduresContext.get(methodName);
          boolean _contains = _get.contains(assertValue);
          if (_contains) {
            _builder_6.append(assertValue, "");
          } else {
            _builder_6.append("\"");
            _builder_6.append(assertValue, "");
            _builder_6.append("\"");
          }
        }
        _builder_6.append(")");
        _builder_6.newLineIfNotEmpty();
        _builder_6.append(" ");
        _builder_6.append("&& !(");
        _builder_6.append(eltName, " ");
        _builder_6.append(".getAttribute(\"value\").contains(");
        {
          List<String> _get_1 = this.proceduresContext.get(methodName);
          boolean _contains_1 = _get_1.contains(assertValue);
          if (_contains_1) {
            _builder_6.append(assertValue, " ");
          } else {
            _builder_6.append("\"");
            _builder_6.append(assertValue, " ");
            _builder_6.append("\"");
          }
        }
        _builder_6.append("))) {");
        _builder_6.newLineIfNotEmpty();
        _builder_6.append("    ");
        _builder_6.append("throw new AssertionError(");
        _builder_6.append(eltName, "    ");
        _builder_6.append(".getAttribute(\"value\") + \" does not contain ");
        _builder_6.append(assertValue, "    ");
        _builder_6.append("\");");
        _builder_6.newLineIfNotEmpty();
        _builder_6.append("};");
        _switchResult_1 = _builder_6;
        break;
      case "equals":
        StringConcatenation _builder_7 = new StringConcatenation();
        _builder_7.append("if(!");
        _builder_7.append(eltName, "");
        _builder_7.append(".getAttribute(\"value\").equals(");
        {
          List<String> _get_2 = this.proceduresContext.get(methodName);
          boolean _contains_2 = _get_2.contains(assertValue);
          if (_contains_2) {
            _builder_7.append(assertValue, "");
          } else {
            _builder_7.append("\"");
            _builder_7.append(assertValue, "");
            _builder_7.append("\"");
          }
        }
        _builder_7.append(")) {");
        _builder_7.newLineIfNotEmpty();
        _builder_7.append("    ");
        _builder_7.append("throw new AssertionError(");
        _builder_7.append(eltName, "    ");
        _builder_7.append(".getAttribute(\"value\") + \" is not equal to ");
        _builder_7.append(assertValue, "    ");
        _builder_7.append("\");");
        _builder_7.newLineIfNotEmpty();
        _builder_7.append("};");
        _switchResult_1 = _builder_7;
        break;
      case "exists":
        StringConcatenation _builder_8 = new StringConcatenation();
        _builder_8.append("if(!");
        _builder_8.append(eltName, "");
        _builder_8.append(".isDisplayed()) {");
        _builder_8.newLineIfNotEmpty();
        _builder_8.append("    ");
        _builder_8.append("throw new AssertionError(");
        _builder_8.append(eltName, "    ");
        _builder_8.append(".getAttribute(\"value\") + \" does not exist\");");
        _builder_8.newLineIfNotEmpty();
        _builder_8.append("};");
        _switchResult_1 = _builder_8;
        break;
      default:
        StringConcatenation _builder_9 = new StringConcatenation();
        _builder_9.append("// FIXME unrecognized assert instruction: assert ");
        String _type_1 = a.getType();
        _builder_9.append(_type_1, "");
        _builder_9.append(" ");
        _builder_9.append(assertValue, "");
        _switchResult_1 = _builder_9;
        break;
    }
    _builder.append(_switchResult_1, "");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final CallProcedure cp, final String method) {
    StringConcatenation _builder = new StringConcatenation();
    String _procedureName = cp.getProcedureName();
    _builder.append(_procedureName, "");
    _builder.append("(");
    EList<String> _parameters = cp.getParameters();
    final Function1<String, String> _function = (String param) -> {
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("\"");
      _builder_1.append(param, "");
      _builder_1.append("\"");
      return _builder_1.toString();
    };
    List<String> _map = ListExtensions.<String, String>map(_parameters, _function);
    String _join = IterableExtensions.join(_map, ", ");
    _builder.append(_join, "");
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Instruction i, final String methodName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("// FIXME wtf is this instruction?");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateInstruction(final Instruction a, final String methodName) {
    if (a instanceof Assert) {
      return _generateInstruction((Assert)a, methodName);
    } else if (a instanceof CallProcedure) {
      return _generateInstruction((CallProcedure)a, methodName);
    } else if (a instanceof Click) {
      return _generateInstruction((Click)a, methodName);
    } else if (a instanceof Fill) {
      return _generateInstruction((Fill)a, methodName);
    } else if (a instanceof Navigate) {
      return _generateInstruction((Navigate)a, methodName);
    } else if (a instanceof Read) {
      return _generateInstruction((Read)a, methodName);
    } else if (a instanceof Select) {
      return _generateInstruction((Select)a, methodName);
    } else if (a instanceof Tick) {
      return _generateInstruction((Tick)a, methodName);
    } else if (a != null) {
      return _generateInstruction(a, methodName);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(a, methodName).toString());
    }
  }
}
