/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.generator;

import com.google.common.collect.Iterables;
import fr.minesnantes.browserautomation.generator.Counter;
import fr.minesnantes.browserautomation.seleniumDSL.Assert;
import fr.minesnantes.browserautomation.seleniumDSL.Click;
import fr.minesnantes.browserautomation.seleniumDSL.Fill;
import fr.minesnantes.browserautomation.seleniumDSL.Instruction;
import fr.minesnantes.browserautomation.seleniumDSL.MainProcedure;
import fr.minesnantes.browserautomation.seleniumDSL.Navigate;
import fr.minesnantes.browserautomation.seleniumDSL.Procedure;
import fr.minesnantes.browserautomation.seleniumDSL.Read;
import fr.minesnantes.browserautomation.seleniumDSL.Select;
import fr.minesnantes.browserautomation.seleniumDSL.SeleniumTest;
import fr.minesnantes.browserautomation.seleniumDSL.Tick;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class SeleniumDSLGenerator extends AbstractGenerator {
  private EList<Procedure> procedures;
  
  private List<String> variables;
  
  private Counter elementCounter;
  
  public List<String> initializeContext() {
    List<String> _xblockexpression = null;
    {
      Counter _counter = new Counter();
      this.elementCounter = _counter;
      ArrayList<String> _arrayList = new ArrayList<String>();
      _xblockexpression = this.variables = _arrayList;
    }
    return _xblockexpression;
  }
  
  public List<String> destroyContext() {
    List<String> _xblockexpression = null;
    {
      this.elementCounter = null;
      _xblockexpression = this.variables = null;
    }
    return _xblockexpression;
  }
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    this.initializeContext();
    EList<EObject> _contents = resource.getContents();
    Iterable<SeleniumTest> _filter = Iterables.<SeleniumTest>filter(_contents, SeleniumTest.class);
    SeleniumTest _head = IterableExtensions.<SeleniumTest>head(_filter);
    CharSequence _generateSeleniumTest = this.generateSeleniumTest(_head);
    fsa.generateFile(
      (("browserautomation" + File.separator) + "SeleniumTest.java"), _generateSeleniumTest);
    this.destroyContext();
  }
  
  public CharSequence generateSeleniumTest(final SeleniumTest st) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package browserautomation;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.openqa.selenium.By;");
    _builder.newLine();
    _builder.append("import org.openqa.selenium.WebDriver;");
    _builder.newLine();
    _builder.append("import org.openqa.selenium.WebElement;");
    _builder.newLine();
    _builder.append("import org.openqa.selenium.chrome.ChromeDriver;");
    _builder.newLine();
    _builder.append("import org.openqa.selenium.support.ui.Select;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class SeleniumTest {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Initialize Selenium web driver for Google Chrome");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("System.setProperty(\"webdriver.chrome.driver\", \"lib/chromedriver\");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("WebDriver webDriver = new ChromeDriver();");
    _builder.newLine();
    _builder.append("        ");
    _builder.newLine();
    {
      MainProcedure _main = st.getMain();
      EList<Instruction> _instructions = _main.getInstructions();
      for(final Instruction i : _instructions) {
        _builder.append("        ");
        CharSequence _generateInstruction = this.generateInstruction(i);
        _builder.append(_generateInstruction, "        ");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("        ");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// Close the browser");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("webDriver.quit();");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Navigate n) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("webDriver.get(\"");
    String _url = n.getUrl();
    _builder.append(_url, "");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Click c) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    final String clickValue = c.getValue();
    _builder.newLineIfNotEmpty();
    CharSequence _switchResult = null;
    String _type = c.getType();
    switch (_type) {
      case "input":
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.append("WebElement ");
        _builder_2.append(eltName, "");
        _builder_2.append(" = webDriver.findElement(By.xpath(\"//input[@value=\\\"");
        _builder_2.append(clickValue, "");
        _builder_2.append("\\\"]\"));");
        _switchResult = _builder_2;
        break;
      case "link":
        StringConcatenation _builder_3 = new StringConcatenation();
        _builder_3.append("WebElement ");
        _builder_3.append(eltName, "");
        _builder_3.append(" = webDriver.findElement(By.linkText(\"");
        _builder_3.append(clickValue, "");
        _builder_3.append("\"));");
        _switchResult = _builder_3;
        break;
      case "xpath":
        StringConcatenation _builder_4 = new StringConcatenation();
        _builder_4.append("WebElement ");
        _builder_4.append(eltName, "");
        _builder_4.append(" = webDriver.findElement(By.xpath(\"");
        _builder_4.append(clickValue, "");
        _builder_4.append("\"));");
        _switchResult = _builder_4;
        break;
      case "name":
        StringConcatenation _builder_5 = new StringConcatenation();
        _builder_5.append("WebElement ");
        _builder_5.append(eltName, "");
        _builder_5.append(" = webDriver.findElement(By.name(\"");
        _builder_5.append(clickValue, "");
        _builder_5.append("\"));");
        _switchResult = _builder_5;
        break;
      default:
        StringConcatenation _builder_6 = new StringConcatenation();
        _builder_6.append("// FIXME unrecognized click instruction: click ");
        String _type_1 = c.getType();
        _builder_6.append(_type_1, "");
        _builder_6.append(" ");
        _builder_6.append(clickValue, "");
        _switchResult = _builder_6;
        break;
    }
    _builder.append(_switchResult, "");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".click();");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Fill f) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    _builder.append("WebElement ");
    _builder.append(eltName, "");
    _builder.append(" = webDriver.findElement(By.name(\"");
    String _name = f.getName();
    _builder.append(_name, "");
    _builder.append("\"));");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".sendKeys(");
    {
      String _value = f.getValue();
      boolean _contains = this.variables.contains(_value);
      if (_contains) {
        String _value_1 = f.getValue();
        _builder.append(_value_1, "");
      } else {
        _builder.append("\"");
        String _value_2 = f.getValue();
        _builder.append(_value_2, "");
        _builder.append("\"");
      }
    }
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Tick t) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    _builder.append("WebElement ");
    _builder.append(eltName, "");
    _builder.append(" = webDriver.findElement(By.name(\"");
    String _name = t.getName();
    _builder.append(_name, "");
    _builder.append("\"));");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".click();");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Select s) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    _builder.append("Select ");
    _builder.append(eltName, "");
    _builder.append(" = new Select(webDriver.findElement(By.name(\"");
    String _name = s.getName();
    _builder.append(_name, "");
    _builder.append("\")));");
    _builder.newLineIfNotEmpty();
    _builder.append(eltName, "");
    _builder.append(".selectByVisibleText(\"");
    String _value = s.getValue();
    _builder.append(_value, "");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Read r) {
    CharSequence _xblockexpression = null;
    {
      String _variable = r.getVariable();
      this.variables.add(_variable);
      StringConcatenation _builder = new StringConcatenation();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("element");
      int _nextCount = this.elementCounter.nextCount();
      _builder_1.append(_nextCount, "");
      final String eltName = _builder_1.toString();
      _builder.newLineIfNotEmpty();
      _builder.append("WebElement ");
      _builder.append(eltName, "");
      _builder.append(" = webDriver.findElement(By.name(\"");
      String _name = r.getName();
      _builder.append(_name, "");
      _builder.append("\"));");
      _builder.newLineIfNotEmpty();
      _builder.append("String ");
      String _variable_1 = r.getVariable();
      _builder.append(_variable_1, "");
      _builder.append(" = ");
      _builder.append(eltName, "");
      _builder.append(".getAttribute(\"value\");");
      _builder.newLineIfNotEmpty();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }
  
  protected CharSequence _generateInstruction(final Assert a) {
    StringConcatenation _builder = new StringConcatenation();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("element");
    int _nextCount = this.elementCounter.nextCount();
    _builder_1.append(_nextCount, "");
    final String eltName = _builder_1.toString();
    _builder.newLineIfNotEmpty();
    final String assertValue = a.getValue();
    _builder.newLineIfNotEmpty();
    _builder.append("WebElement ");
    _builder.append(eltName, "");
    _builder.append(" = webDriver.findElement(By.name(\"");
    String _name = a.getName();
    _builder.append(_name, "");
    _builder.append("\"));");
    _builder.newLineIfNotEmpty();
    CharSequence _switchResult = null;
    String _type = a.getType();
    switch (_type) {
      case "contains":
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.append("if(!");
        _builder_2.append(eltName, "");
        _builder_2.append(".getAttribute(\"value\").contains(");
        {
          boolean _contains = this.variables.contains(assertValue);
          if (_contains) {
            _builder_2.append(assertValue, "");
          } else {
            _builder_2.append("\"");
            _builder_2.append(assertValue, "");
            _builder_2.append("\"");
          }
        }
        _builder_2.append(")) {");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("throw new AssertionError(");
        _builder_2.append(eltName, "    ");
        _builder_2.append(".getAttribute(\"value\") + \" does not contain ");
        _builder_2.append(assertValue, "    ");
        _builder_2.append("\");");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("};");
        _switchResult = _builder_2;
        break;
      case "equals":
        StringConcatenation _builder_3 = new StringConcatenation();
        _builder_3.append("if(!");
        _builder_3.append(eltName, "");
        _builder_3.append(".getAttribute(\"value\").equals(");
        {
          boolean _contains_1 = this.variables.contains(assertValue);
          if (_contains_1) {
            _builder_3.append(assertValue, "");
          } else {
            _builder_3.append("\"");
            _builder_3.append(assertValue, "");
            _builder_3.append("\"");
          }
        }
        _builder_3.append(")) {");
        _builder_3.newLineIfNotEmpty();
        _builder_3.append("    ");
        _builder_3.append("throw new AssertionError(");
        _builder_3.append(eltName, "    ");
        _builder_3.append(".getAttribute(\"value\") + \" is not equal to ");
        _builder_3.append(assertValue, "    ");
        _builder_3.append("\");");
        _builder_3.newLineIfNotEmpty();
        _builder_3.append("};");
        _switchResult = _builder_3;
        break;
      case "exists":
        StringConcatenation _builder_4 = new StringConcatenation();
        _builder_4.append("if(!");
        _builder_4.append(eltName, "");
        _builder_4.append(".isDisplayed()) {");
        _builder_4.newLineIfNotEmpty();
        _builder_4.append("    ");
        _builder_4.append("throw new AssertionError(");
        _builder_4.append(eltName, "    ");
        _builder_4.append(".getAttribute(\"value\") + \" does not exist\");");
        _builder_4.newLineIfNotEmpty();
        _builder_4.append("};");
        _switchResult = _builder_4;
        break;
      default:
        StringConcatenation _builder_5 = new StringConcatenation();
        _builder_5.append("// FIXME unrecognized assert instruction: assert ");
        String _type_1 = a.getType();
        _builder_5.append(_type_1, "");
        _builder_5.append(" ");
        _builder_5.append(assertValue, "");
        _switchResult = _builder_5;
        break;
    }
    _builder.append(_switchResult, "");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  protected CharSequence _generateInstruction(final Instruction i) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("// FIXME wtf is this instruction?");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence generateInstruction(final Instruction a) {
    if (a instanceof Assert) {
      return _generateInstruction((Assert)a);
    } else if (a instanceof Click) {
      return _generateInstruction((Click)a);
    } else if (a instanceof Fill) {
      return _generateInstruction((Fill)a);
    } else if (a instanceof Navigate) {
      return _generateInstruction((Navigate)a);
    } else if (a instanceof Read) {
      return _generateInstruction((Read)a);
    } else if (a instanceof Select) {
      return _generateInstruction((Select)a);
    } else if (a instanceof Tick) {
      return _generateInstruction((Tick)a);
    } else if (a != null) {
      return _generateInstruction(a);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(a).toString());
    }
  }
}
