/**
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.seleniumDSL.tests;

import fr.minesnantes.browserautomation.seleniumDSL.SeleniumDSLFactory;
import fr.minesnantes.browserautomation.seleniumDSL.SeleniumTest;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Selenium Test</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class SeleniumTestTest extends TestCase {

	/**
	 * The fixture for this Selenium Test test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SeleniumTest fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(SeleniumTestTest.class);
	}

	/**
	 * Constructs a new Selenium Test test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SeleniumTestTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Selenium Test test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(SeleniumTest fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Selenium Test test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SeleniumTest getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SeleniumDSLFactory.eINSTANCE.createSeleniumTest());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //SeleniumTestTest
