/*
 * generated by Xtext 2.10.0
 */
package fr.minesnantes.browserautomation.ui.tests;

import com.google.inject.Injector;
import fr.minesnantes.browserautomation.ui.internal.BrowserautomationActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SeleniumDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BrowserautomationActivator.getInstance().getInjector("fr.minesnantes.browserautomation.SeleniumDSL");
	}

}
